version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: jintsu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jintsu_app
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres-data: